#name: Platform CI/CD
#
#on:
#  push:
#    branches:
#      - main
#
#jobs:
#  build-and-deploy:
#    runs-on: ubuntu-latest
#
#    steps:
#      # 1. 检出代码
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      # 2. 设置 JDK 17
#      - name: Set up JDK 17
#        uses: actions/setup-java@v4
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#
#      # 3. 使用 Maven 构建项目
#      - name: Build with Maven
#        run: mvn clean install -DskipTests
#
#      # 4. 验证 JAR 文件是否存在
#      - name: Check JAR file
#        run: |
#          ls -l target/
#          if [ ! -f "target/platform.jar" ]; then
#            echo "Error: target/platform.jar not found"
#            exit 1
#          fi
#
#      # 5. 将构建的 JAR 文件传输到服务器
#      - name: Copy JAR to server
#        uses: appleboy/scp-action@v0.1.4
#        with:
#          host: ${{ secrets.SERVER_HOST }}
#          username: ${{ secrets.SERVER_USERNAME }}
#          password: ${{ secrets.SERVER_PASSWORD }}
#          port: ${{ secrets.SERVER_PORT }}
#          source: "target/platform.jar"
#          target: "/root/source/repo/target/"
#
#      # 6. 执行服务器上的部署脚本
#      - name: Deploy to server
#        uses: appleboy/ssh-action@v1.0.0
#        with:
#          host: ${{ secrets.SERVER_HOST }}
#          username: ${{ secrets.SERVER_USERNAME }}
#          password: ${{ secrets.SERVER_PASSWORD }}
#          port: ${{ secrets.SERVER_PORT }}
#          script: |
#            cd /root/platform
#            chmod +x deploy.sh
#            ./deploy.sh || { cat platform.log; exit 1; }